### ISSUE TITLE
Left / Right icons are not working when selecting year

### ISSUE THREAD

**Issue by hlavacek** [chingyawhao/material-ui-next-pickers#2]
In the date picker, when clicking on the header to move through years, the left and right icons are not working, it stays on the same page.

It can be seen even on the demo page: http://chingyawhao.github.io/material-ui-pickers

Tested in Chrome on mac.

**Comment by chingyawhao** [comment]
Thanks @hlavacek,

Its my bad, sorry...I forgot to set pointer-events all to the buttons

Fixed at 0.0.7
