### ISSUE TITLE
v0.0.15 DateFormatInput Display Issues

### ISSUE THREAD

**Issue by ideoclickVanessa** [chingyawhao/material-ui-next-pickers#20]
Using v0.0.15 of this package, I'm running into the display issues demostrated in this screenshot:
![displayissue](https://user-images.githubusercontent.com/44000426/46880513-ac8ad600-cdfd-11e8-952a-85b7a0bb3307.png) from Chrome

The pickers in the screenshot were rendered using this code:
```
<DateFormatInput
	fullWidth={false}
	label="Start Date"
	name="startDateInput"
	onChange={this.handleStartDateChange}
	value={this.state.startDate}
/>
<DateFormatInput
	fullWidth={false}
	label="End Date"
	name="endDateInput"
	onChange={this.handleEndDateChange}
	value={this.state.endDate}
/>
```

It seems that the current height of the Input (set at 19px) is a bit too small. Manipulating it within Chrome seems to indicate that 25px would be better. The DateFormatInput control also doesn't seem honor the fullWidth prop since passing `fullWidth={false}` has no effect.

**Comment by ideoclickVanessa** [comment]
The styling gets even worse after running the production build via:
```
npm run build
serve -l 3000 -s build
```
as seen here:
![proddisplayissue](https://user-images.githubusercontent.com/44000426/46895930-72d2c300-ce2f-11e8-80b5-58059194150b.png) in Chrome created by https://gist.github.com/ideoclickVanessa/4820f8f8eb8baf581ac5ba1e821852a9

My actual app actually fails to render the entire React tree when the DateFormatInput is mounted into it with the prod build.

**Comment by chingyawhao** [comment]
Might be an issue related to https://material-ui.com/getting-started/faq/#why-aren-39-t-my-components-rendering-correctly-in-production-builds

**Comment by patorjk** [comment]
I was having the same display issue as the OP. It may be a browser version issue, as I'm working in older browsers (Chrome v73, Firefox v31.5.0).

I was able to fix the issue by wrapping the control in a div that had a style property of "box-sizing: content-box".
