### ISSUE TITLE
In production mode UI is crushed

### ISSUE THREAD

**Issue by Nusinka** [chingyawhao/material-ui-next-pickers#24]
In developer mode all work nice. But after doing a production build UI (on pages where I use this picker) is crushed. I use create-react-app. If I'm commenting this picker - all looks good.

**Comment by chingyawhao** [comment]
Can you send me some screenshots and with console output?

**Comment by chingyawhao** [comment]
Found the issue
Its regarding https://material-ui.com/getting-started/faq/#why-aren-39-t-my-components-rendering-correctly-in-production-builds
Fixed with the latest release
