### ISSUE TITLE
Allow to pass disabled flag

### ISSUE THREAD

**Issue by hlavacek** [chingyawhao/material-ui-next-pickers#3]
Would it be possible to allow passing of disabled flag for the input? Right now it is not possible to disable it.

**Comment by chingyawhao** [comment]
Exposed 0.0.8 along with a bunch of other features

**Comment by hlavacek** [comment]
This is still not working as expected, it disables the input field, but the icon is still clickable and the input value can be changed.

**Comment by Abdulsemed** [comment]
I am having a problem on disabling the picker as well. `disable={true}` just changes the color to grey but the icon and input are clickable.

**Comment by chingyawhao** [comment]
Sorry guys...my bad
Please check on version 0.0.20
